<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NaruttoTimer.Rules\NaruttoTimer.Rules.csproj" />
    <ProjectReference Include="..\NaruttoTimer.Capture\NaruttoTimer.Capture.csproj" />
    <ProjectReference Include="..\NaruttoTimer.Data\NaruttoTimer.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.30.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- ExcludeFromSingleFile：模型按磁盘路径 AppContext.BaseDirectory\assets 读取，不能打进单文件包 -->
    <None Update="assets\**" CopyToOutputDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
  </ItemGroup>

</Project>
